language: go

go: 
  - 1.6
  - 1.7
  - tip

install:
  - go get -u github.com/davecgh/go-spew/spew
  - go get -u github.com/cat2neat/gopeek

script:
  - go test -v -covermode=count -coverprofile=profile.cov
after_success:
    - go get -v github.com/mattn/goveralls
    - export PATH=$PATH:$HOME/gopath/bin
    - goveralls -coverprofile=profile.cov -service=travis-ci
